### ISSUE TITLE
Does that work ?

### ISSUE THREAD

**Issue by m4hdi1995** [turtlecoin/turtlecoin-webwallet-js#5]
Hello , just wanted to know if someone tested this wallet and it works for turtle , thanks.

**Comment by davehlong** [comment]
Hi, yes, it was tested and does work for turtle. Are you having issues ?

**Comment by m4hdi1995** [comment]
i didn't test it , i was going to adapt it to work with other coin , just wanted to know if it's functional, thanks for your answer.

**Comment by davehlong** [comment]
ok, just be aware this version is setup specifically for bytecoin block/transaction types (forks of Turtlecoin) - if you've forked from Monero or a Monero Clone, then you will need to get a version that supports RingCT. (ie: from Masari, the original developers)
