### ISSUE TITLE
wallet issues - credit issues

### ISSUE THREAD

**Issue by LeinAd2k** [turtlecoin/turtlecoin-webwallet-js#8]
Hey there,
i have forked your wallet, cause i want to build it for some other coins. I have setup an testbuild and get an error:
when i send coins to the webwallet, they are displayed as pending but after a while they disappear. however, when i restore the webwallet with the client, the coins are present.
I can't send the coins from the webwallet because it says that there is no credit available.

**Comment by davehlong** [comment]
Hi - please see note on main readme here: https://github.com/turtlecoin/turtlecoin-webwallet-js#note-this-project-is-a-work-under-construction---it-is-not-fully-functional---do-not-expect-everything-or-anything-to-work-straight-out-of-the-box

We are currently working on a re-write of a number of aspects of this wallet, where these issues will be resolved. Please bear with us while we complete the updates.

**Comment by LeinAd2k** [comment]
works it for turtle (showing the amount correct) right ?

**Comment by davehlong** [comment]
Yes, sync'ing works fine - but, as mentioned, we are busy changing this (and other) aspects of this wallet.

If it's not sync'ing, it's most likely your cache is not building correctly. Check that you have started your Node in BlockExplorer mode 

`$ .\CoinDaemon --enable-blockexplorer --enable-core "*"` 

- then, check the app.settings file to ensure you have the correct connection details for the app to connect to your daemon.

To varify, you should then see files named "transactions-1-10000.db starting to grow within the "App_Data" folder of your published app's root folder.

**Comment by LeinAd2k** [comment]
this file is not Building up :-/. daemon is in Explorer mode

**Comment by LeinAd2k** [comment]
hm.. i dont know what i have done but the files are in the correct Folder now.. they have to sync compelte, bevor the wallet is working fine, Right? (dotnet crashes sometimes)

**Comment by Nash-Cash** [comment]
I have a question too. Where to Change Coin decimals? In config.ts i changed from 2 to 8 but nothing happens

**Comment by brandonlehmann** [comment]
Stale fork issue.
