### ISSUE TITLE
Sync bar stuck at 0% 

### ISSUE THREAD

**Issue by blockinator** [turtlecoin/turtlecoin-webwallet-js#9]
I deployed the web wallet onto an Ubuntu 16.04 server as shown in the `Deploy_Ubuntu_Instructions.txt` file. I was able to get the stats to show on the `Network` page but on the `Account` page it shows that the wallet isn't syncing. It's stuck at 0%. There's no browsers errors just warnings.

**Comment by zpalmtree** [comment]
This repo hasn't been updated in around 10 months. I think you'll have to perform some modifications of your own to get it functioning.
